eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

filterUrls:
  services: /api/manage/,/api/upload/,/api/push/,/api/workflow/
  excludes: /api/upload/uploadFile,/api/push/push,/api/push/chat
  apis: /api/manage/user/captcha,/api/manage/user/login,/api/manage/user/qrcode,/api/manage/user/qrcodeLogin
  origins: http://localhost,http://localhost:8888,http://localhost:8880,http://47.100.119.102

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout:30000
              ConnectTimeout:30000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

safeApis:
safeDomains:

server:
  port: 8201
  servlet:
    contextPath: /

spring:
  application:
    name: lxt-gateway
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  resources:
    static-locations: classpath:/templates/
zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    lxt-push:
      path: /api/push/**
      serviceId: lxt-push
      stripPrefix: true
    lxt-upload:
      path: /api/upload/**
      serviceId: lxt-upload
      stripPrefix: true
    lxt-manage:
      path: /api/manage/**
      serviceId: lxt-manage
      stripPrefix: true
    lxt-workflow:
      path: /api/workflow/**
      serviceId: lxt-workflow
      stripPrefix: true